export enum LocationType {
  MainBoardSpot = 1,
  MainBoardStackSpace,
  FavorBoardSpot,
  FavorBoardSpace,
  ScoreBoardSpot,
  ScoreBoardSpace,
  ProjectCardsDeck,
  ProjectCardsDisplay,
  PlayerBoardSpot,
  PlayerBoardStackSpace,
  ScoreRangeAreaSpace,
  PlayerArchitectsSupply,
  PlayerPawnsSupply,
  FirstPlayerCardSpot,
  PlayerBuildingCardsSpot,
  PlayerProjectCardsSpot,
  PlayerValidatedProjectCardsPile,
  InHandSpotLocator
}
